export default {
    pageBackground: '#f0f0f0',
    mainFont: '"Noto Sans JP", "Noto Sans", sans-serif',
    headerColor: '#087FA3',
    cardTextColor: '#FFFFFF',
    cardBgColor0: '#FFC500',
    cardBgColor1: '#DD5500',
    cardBgColor2: '#087FA3',
    expandedCardBgColor: '#FAF7ED',
    kanaTableBorder: '1px solid #99B1B8',
    kanaTableRowHoverColor: '#DDEAEA',
    kanaTableRowSelectedColor: '#DDF8DD',
    kanaTableCellColor: '#000000',
    kanaTableCellColor2: 'grey',
};
